clone_depth: 1
version: '{build}'
image: Visual Studio 2019
test: off
skip_non_tags: true
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1 -Target DeployFrameworkXamarin
deploy:
  - provider: Environment
    name: nuget
  - provider: Environment
    name: github
