# This is a workaround to allow PRs to report their coverage. This will run inside the base repository.
# See:
#   * https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories
#   * https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
name: "Test Report"
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Continuous Integration Test Report
        uses: dorny/test-reporter@v1.4.2
        with:
          artifact: osu-framework-test-results
          name: Test Results
          path: "*.trx"
          reporter: dotnet-trx
